/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ACol: typeof import('ant-design-vue/es')['Col']
    ALayout: typeof import('ant-design-vue/es')['Layout']
    ALayoutContent: typeof import('ant-design-vue/es')['LayoutContent']
    ALayoutFooter: typeof import('ant-design-vue/es')['LayoutFooter']
    AModal: typeof import('ant-design-vue/es')['Modal']
    ARow: typeof import('ant-design-vue/es')['Row']
    ASwitch: typeof import('ant-design-vue/es')['Switch']
    Footer: typeof import('./src/components/Footer.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
